// Tipos compartidos para coaches basados en el diagrama de BD
export interface Coach {
  id: number;
  userId: string;
  displayname: string;
  specialties: string;
  rating: number;
  city: string;
  country: string;
  status: 'Disponible' | 'Ocupado' | 'Desconectado';
  reviewsCount: number;
  bio: string;
  avatarColor: string;
  profileimage?: string;
  reviews: {
    name: string;
    date: string;
    stars: number;
    comment: string;
  }[];
}

// Datos simulados que imitan la estructura de la base de datos
export const mockCoachesData: Coach[] = [
  {
    id: 1,
    userId: 'uuid-user-1',
    displayname: 'Carlos Mendoza',
    specialties: 'Mecánica Automotriz',
    rating: 4.8,
    city: 'Bogotá',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 127,
    bio: 'Especialista en mecánica automotriz con más de 10 años de experiencia. Me especializo en diagnósticos complejos y reparaciones de motores. He trabajado con una amplia variedad de marcas y modelos, desde vehículos clásicos hasta los más modernos con tecnología híbrida y eléctrica.',
    reviews: [
      {
        name: 'Juan Carlos',
        date: 'hace 2 días',
        stars: 5,
        comment: 'Excelente sesión, resolvió mi problema rápidamente.',
      },
      {
        name: 'María López',
        date: 'hace 1 semana',
        stars: 5,
        comment: 'Súper recomendado, muy profesional.',
      },
    ],
    avatarColor: 'text-blue-400',
  },
  {
    id: 2,
    userId: 'uuid-user-2',
    displayname: 'María García',
    specialties: 'Psicología Clínica',
    rating: 4.9,
    city: 'Medellín',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 203,
    bio: 'Psicóloga con enfoque humanista, especializada en terapia cognitivo-conductual y manejo de ansiedad. Cuento con más de 15 años de experiencia ayudando a personas a superar sus desafíos emocionales y mentales. Mi objetivo es crear un espacio seguro donde puedas explorar tus pensamientos y sentimientos.',
    reviews: [
      {
        name: 'Ana Sofía',
        date: 'hace 1 día',
        stars: 5,
        comment: 'María es increíble, me ayudó muchísimo.',
      },
      {
        name: 'Pedro R.',
        date: 'hace 3 semanas',
        stars: 5,
        comment: 'Una gran profesional, muy empática.',
      },
    ],
    avatarColor: 'text-pink-400',
  },
  {
    id: 3,
    userId: 'uuid-user-3',
    displayname: 'Ana Silva',
    specialties: 'Pintura y Arte',
    rating: 4.7,
    city: 'Cali',
    country: 'Colombia',
    status: 'Ocupado',
    reviewsCount: 89,
    bio: 'Artista profesional y profesora de pintura con técnicas tradicionales y modernas. He dedicado mi vida al arte, explorando diferentes medios y estilos. Me encanta compartir mi conocimiento y ayudar a otros a descubrir su creatividad a través del color y la forma.',
    reviews: [
      {
        name: 'Laura M.',
        date: 'hace 5 días',
        stars: 5,
        comment: 'Excelente maestra, muy paciente.',
      },
    ],
    avatarColor: 'text-purple-400',
  },
  {
    id: 4,
    userId: 'uuid-user-4',
    displayname: 'Luis Ramírez',
    specialties: 'Programación Web',
    rating: 4.6,
    city: 'Barranquilla',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 156,
    bio: 'Desarrollador Full Stack con experiencia en React, Node.js y bases de datos modernas. He trabajado en proyectos desde startups hasta grandes corporaciones. Mi pasión es enseñar programación de manera práctica y accesible, ayudando a otros a construir aplicaciones web increíbles.',
    reviews: [
      {
        name: 'Carlos T.',
        date: 'hace 3 días',
        stars: 4,
        comment: 'Muy buen coach, explica muy bien.',
      },
      {
        name: 'Sofia L.',
        date: 'hace 1 semana',
        stars: 5,
        comment: 'Luis me ayudó a entender React perfectamente.',
      },
    ],
    avatarColor: 'text-green-400',
  },
  {
    id: 5,
    userId: 'uuid-user-5',
    displayname: 'Andrea Morales',
    specialties: 'Nutrición y Dietética',
    rating: 4.9,
    city: 'Bucaramanga',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 234,
    bio: 'Nutricionista certificada especializada en pérdida de peso, nutrición deportiva y hábitos alimenticios saludables. Te ayudo a crear un plan personalizado que se adapte a tu estilo de vida y objetivos.',
    reviews: [
      {
        name: 'Laura K.',
        date: 'hace 2 días',
        stars: 5,
        comment: 'Andrea me ayudó a perder 15kg de forma saludable.',
      },
    ],
    avatarColor: 'text-emerald-400',
  },
  {
    id: 6,
    userId: 'uuid-user-6',
    displayname: 'Roberto Díaz',
    specialties: 'Entrenamiento Personal',
    rating: 4.7,
    city: 'Pereira',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 189,
    bio: 'Entrenador personal certificado con 8 años de experiencia. Especializado en fitness funcional, pérdida de peso y ganancia de masa muscular. Diseño rutinas personalizadas para todos los niveles.',
    reviews: [
      {
        name: 'Miguel A.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Excelente entrenador, muy motivador.',
      },
    ],
    avatarColor: 'text-orange-400',
  },
  {
    id: 7,
    userId: 'uuid-user-7',
    displayname: 'Carmen Vega',
    specialties: 'Coaching Profesional',
    rating: 4.8,
    city: 'Cartagena',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 167,
    bio: 'Coach profesional certificada en desarrollo de carrera y liderazgo. Ayudo a profesionales a alcanzar sus metas laborales, mejorar su liderazgo y encontrar su propósito profesional.',
    reviews: [
      {
        name: 'David R.',
        date: 'hace 4 días',
        stars: 5,
        comment: 'Carmen me ayudó a conseguir mi ascenso.',
      },
    ],
    avatarColor: 'text-indigo-400',
  },
  {
    id: 8,
    userId: 'uuid-user-8',
    displayname: 'Javier Herrera',
    specialties: 'Yoga y Mindfulness',
    rating: 4.9,
    city: 'Manizales',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 198,
    bio: 'Instructor de yoga certificado con formación en mindfulness y meditación. Te guío en el camino hacia el bienestar físico y mental a través de prácticas ancestrales adaptadas al mundo moderno.',
    reviews: [
      {
        name: 'Isabella M.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Las sesiones con Javier son transformadoras.',
      },
    ],
    avatarColor: 'text-teal-400',
  },
  {
    id: 9,
    userId: 'uuid-user-9',
    displayname: 'Lucía Fernández',
    specialties: 'Terapia de Pareja',
    rating: 4.8,
    city: 'Ibagué',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 143,
    bio: 'Psicóloga especializada en terapia de pareja y familia. Ayudo a parejas a mejorar su comunicación, resolver conflictos y fortalecer su relación a través de técnicas terapéuticas efectivas.',
    reviews: [
      {
        name: 'Carlos & Ana',
        date: 'hace 3 días',
        stars: 5,
        comment: 'Lucía salvó nuestra relación. Muy profesional.',
      },
    ],
    avatarColor: 'text-rose-400',
  },
  {
    id: 10,
    userId: 'uuid-user-10',
    displayname: 'Fernando Castro',
    specialties: 'Coaching Financiero',
    rating: 4.7,
    city: 'Santa Marta',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 176,
    bio: 'Asesor financiero y coach especializado en planificación financiera personal, ahorro e inversiones. Te ayudo a organizar tus finanzas y alcanzar la libertad financiera.',
    reviews: [
      {
        name: 'Patricia L.',
        date: 'hace 2 días',
        stars: 4,
        comment: 'Fernando me enseñó a ahorrar e invertir.',
      },
    ],
    avatarColor: 'text-yellow-400',
  },
  {
    id: 11,
    userId: 'uuid-user-11',
    displayname: 'Natalia Ruiz',
    specialties: 'Inglés Conversacional',
    rating: 4.9,
    city: 'Villavicencio',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 267,
    bio: 'Profesora de inglés nativa con certificación TEFL. Especializada en inglés conversacional para profesionales. Mis clases son dinámicas y enfocadas en situaciones reales del día a día.',
    reviews: [
      {
        name: 'Andrés P.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Natalia me ayudó a mejorar mi inglés para el trabajo.',
      },
    ],
    avatarColor: 'text-blue-500',
  },
  {
    id: 12,
    userId: 'uuid-user-12',
    displayname: 'Diego Montoya',
    specialties: 'Marketing Digital',
    rating: 4.6,
    city: 'Cúcuta',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 134,
    bio: 'Especialista en marketing digital con experiencia en redes sociales, Google Ads y estrategias de contenido. Ayudo a emprendedores y empresas a crecer en el mundo digital.',
    reviews: [
      {
        name: 'Camila S.',
        date: 'hace 5 días',
        stars: 4,
        comment: 'Diego mejoró significativamente mis ventas online.',
      },
    ],
    avatarColor: 'text-purple-500',
  },
  {
    id: 13,
    userId: 'uuid-user-13',
    displayname: 'Valeria Gómez',
    specialties: 'Música y Piano',
    rating: 4.8,
    city: 'Armenia',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 156,
    bio: 'Pianista profesional y profesora de música con 12 años de experiencia. Enseño piano para principiantes y avanzados, teoría musical y composición. La música transforma vidas.',
    reviews: [
      {
        name: 'Sebastián R.',
        date: 'hace 2 días',
        stars: 5,
        comment: 'Valeria es una excelente profesora de piano.',
      },
    ],
    avatarColor: 'text-violet-400',
  },
  {
    id: 14,
    userId: 'uuid-user-14',
    displayname: 'Álvaro Sánchez',
    specialties: 'Fotografía Profesional',
    rating: 4.7,
    city: 'Pasto',
    country: 'Colombia',
    status: 'Ocupado',
    reviewsCount: 112,
    bio: 'Fotógrafo profesional especializado en retratos, bodas y fotografía comercial. Te enseño técnicas de composición, manejo de luz y edición para que captures momentos únicos.',
    reviews: [
      {
        name: 'Melissa T.',
        date: 'hace 1 semana',
        stars: 5,
        comment: 'Álvaro me enseñó todo sobre fotografía de retratos.',
      },
    ],
    avatarColor: 'text-gray-400',
  },
  {
    id: 15,
    userId: 'uuid-user-15',
    displayname: 'Paola Jiménez',
    specialties: 'Repostería y Panadería',
    rating: 4.9,
    city: 'Popayán',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 189,
    bio: 'Chef pastelera con especialización en repostería francesa y panadería artesanal. Te enseño desde técnicas básicas hasta creaciones gourmet para que hornees como un profesional.',
    reviews: [
      {
        name: 'Juliana F.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Paola me enseñó a hacer pasteles increíbles.',
      },
    ],
    avatarColor: 'text-pink-500',
  },
  {
    id: 16,
    userId: 'uuid-user-16',
    displayname: 'Mauricio López',
    specialties: 'Carpintería y Ebanistería',
    rating: 4.6,
    city: 'Tunja',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 87,
    bio: 'Maestro carpintero con 20 años de experiencia en carpintería fina y ebanistería. Enseño desde técnicas básicas hasta proyectos avanzados para crear muebles únicos.',
    reviews: [
      {
        name: 'Ricardo M.',
        date: 'hace 3 días',
        stars: 4,
        comment: 'Mauricio me enseñó a trabajar la madera como un experto.',
      },
    ],
    avatarColor: 'text-amber-600',
  },
  {
    id: 17,
    userId: 'uuid-user-17',
    displayname: 'Gabriela Torres',
    specialties: 'Diseño Gráfico',
    rating: 4.8,
    city: 'Montería',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 145,
    bio: 'Diseñadora gráfica con experiencia en branding, diseño web y ilustración digital. Te ayudo a desarrollar tu creatividad y dominar herramientas como Photoshop, Illustrator y Figma.',
    reviews: [
      {
        name: 'Alejandro V.',
        date: 'hace 2 días',
        stars: 5,
        comment: 'Gabriela me ayudó a crear la identidad de mi empresa.',
      },
    ],
    avatarColor: 'text-cyan-400',
  },
  {
    id: 18,
    userId: 'uuid-user-18',
    displayname: 'Cristian Moreno',
    specialties: 'Emprendimiento y Startups',
    rating: 4.7,
    city: 'Neiva',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 198,
    bio: 'Emprendedor serial y mentor de startups. He fundado 3 empresas exitosas y ayudo a otros emprendedores a validar ideas, conseguir financiación y escalar sus negocios.',
    reviews: [
      {
        name: 'Mónica H.',
        date: 'hace 4 días',
        stars: 5,
        comment: 'Cristian me ayudó a lanzar mi startup exitosamente.',
      },
    ],
    avatarColor: 'text-red-500',
  },
  {
    id: 19,
    userId: 'uuid-user-19',
    displayname: 'Sandra Rojas',
    specialties: 'Costura y Confección',
    rating: 4.8,
    city: 'Sincelejo',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 167,
    bio: 'Modista profesional con 15 años de experiencia. Enseño desde costura básica hasta alta costura, patronaje y confección de prendas únicas. Convierte tu creatividad en arte textil.',
    reviews: [
      {
        name: 'Claudia P.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Sandra me enseñó a coser mis propias prendas.',
      },
    ],
    avatarColor: 'text-fuchsia-400',
  },
  {
    id: 20,
    userId: 'uuid-user-20',
    displayname: 'Esteban Vargas',
    specialties: 'Jardinería y Paisajismo',
    rating: 4.6,
    city: 'Florencia',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 123,
    bio: 'Paisajista y experto en jardinería sostenible. Te enseño a crear y mantener jardines hermosos, huertos urbanos y espacios verdes que conecten con la naturaleza.',
    reviews: [
      {
        name: 'Martha L.',
        date: 'hace 2 días',
        stars: 4,
        comment: 'Esteban transformó mi patio en un jardín espectacular.',
      },
    ],
    avatarColor: 'text-lime-500',
  },
  {
    id: 21,
    userId: 'uuid-user-21',
    displayname: 'Sofía Herrera',
    specialties: 'Danza y Coreografía',
    rating: 4.9,
    city: 'Riohacha',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 178,
    bio: 'Bailarina profesional y coreógrafa especializada en danzas latinas, ballet y danza contemporánea. Te ayudo a expresarte a través del movimiento y mejorar tu técnica.',
    reviews: [
      {
        name: 'Valentina C.',
        date: 'hace 1 día',
        stars: 5,
        comment: 'Sofía me ayudó a ganar confianza bailando.',
      },
    ],
    avatarColor: 'text-pink-400',
  },
  {
    id: 22,
    userId: 'uuid-user-22',
    displayname: 'Raúl Medina',
    specialties: 'Electricidad Doméstica',
    rating: 4.7,
    city: 'Quibdó',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 156,
    bio: 'Electricista certificado con 18 años de experiencia. Enseño instalaciones eléctricas seguras, mantenimiento y reparaciones básicas para el hogar y pequeños negocios.',
    reviews: [
      {
        name: 'Jorge A.',
        date: 'hace 3 días',
        stars: 4,
        comment: 'Raúl me enseñó a hacer instalaciones eléctricas seguras.',
      },
    ],
    avatarColor: 'text-yellow-500',
  },
  {
    id: 23,
    userId: 'uuid-user-23',
    displayname: 'Beatriz Aguirre',
    specialties: 'Organización y Productividad',
    rating: 4.8,
    city: 'Valledupar',
    country: 'Colombia',
    status: 'Disponible',
    reviewsCount: 201,
    bio: 'Consultora en organización personal y productividad. Te ayudo a organizar tu espacio, gestionar tu tiempo eficientemente y crear sistemas que te permitan ser más productivo.',
    reviews: [
      {
        name: 'Antonio R.',
        date: 'hace 2 días',
        stars: 5,
        comment: 'Beatriz cambió mi vida organizándome mejor.',
      },
    ],
    avatarColor: 'text-slate-500',
  },
];
