/**
 * Utilities Index
 *
 * Exporta todas las utilidades del proyecto organizadas por categoría.
 * Incluye Singletons, formatters, validators, y otras herramientas.
 */

// Singletons
export { ConfigManager } from './ConfigManager';
export { CacheManager } from './CacheManager';

// Date utilities
export {
  DateFormatter,
  formatDate,
  formatTime,
  formatDateTime,
  formatRelativeTime,
  parseDate,
  isValidDate,
  addDays,
  subtractDays,
  getDaysDifference,
  isToday,
  isTomorrow,
  isYesterday,
  isThisWeek,
  isThisMonth,
  getTimeZone,
  convertTimeZone,
  formatSessionDate,
  getSessionDuration,
  isSessionTime,
  getAvailableTimeSlots,
} from './dateFormatter';

// String utilities
export {
  StringFormatter,
  capitalize,
  camelCase,
  pascalCase,
  kebabCase,
  snakeCase,
  truncate,
  removeAccents,
  generateSlug,
  maskEmail,
  maskPhone,
  validateEmail,
  validatePhone,
  extractInitials,
  pluralize,
  singularize,
  highlightText,
  stripHtml,
  escapeHtml,
  unescapeHtml,
  similarity,
  formatCoachName,
  generateUsername,
  formatSessionTitle,
  parseSearchQuery,
  formatSkills,
  abbreviate,
  wordCount,
  readingTime,
  sanitizeInput,
  formatPrice,
  formatRating,
  generateSessionCode,
  isValidSessionCode,
} from './stringFormatter';

// Number utilities
export {
  NumberFormatter,
  formatCurrency,
  formatPercentage,
  formatFileSize,
  formatNumber,
  parseNumber,
  isNumeric,
  roundToDecimals,
  clamp,
  randomInt,
  randomFloat,
  generateId,
  normalizeToRange,
  getPercentileRank,
  calculateGrowthRate,
  formatCoachPrice,
  formatSessionDuration,
  formatCredits,
  formatDistance,
  calculateAverage,
  calculateMedian,
  calculateStandardDeviation,
  calculatePercentile,
  isValidRating,
  isValidPrice,
  isValidCredits,
  isValidDuration,
  formatMetric,
  formatTrend,
  formatCompactNumber,
  convertCurrency,
  convertUnits,
} from './numberFormatter';

// Validation utilities
export {
  ValidationUtils,
  BaseValidator,
  isRequired,
  minLength,
  maxLength,
  isEmail,
  isPhone,
  isUrl,
  isDate,
  isPositiveNumber,
  isInteger,
  isBetween,
  matchesRegex,
  isValidRating as validationIsValidRating,
  isValidSkills,
  isValidSessionDate,
  isValidPrice as validationIsValidPrice,
  createValidator,
  combineValidators,
  conditionalValidator,
  dependentValidator,
  createAsyncValidator,
  isUniqueEmail,
  isValidCoachAvailability,
  validateForm,
  validateFormAsync,
  hasFormErrors,
  getFirstError,
  validateCoachProfile,
  validateSessionBooking,
  validateUserRegistration,
} from './validationUtils';

// Array utilities
export {
  ArrayUtils,
  groupBy,
  sortBy,
  filterBy,
  unique,
  chunk,
  flatten,
  intersection,
  difference,
  shuffle,
  sample,
  partition,
  pluck,
  sum,
  average,
  median,
  mode,
  sortCoachesByRating,
  filterAvailableCoaches,
  groupSessionsByDate,
  getTopRatedCoaches,
  searchCoaches,
} from './arrayUtils';

// Object utilities
export {
  ObjectUtils,
  deepClone,
  deepMerge,
  pick,
  omit,
  flattenObject,
  unflattenObject,
  getNestedValue,
  setNestedValue,
  hasProperty,
  isEmpty,
  isEqual,
  transform,
  mapKeys,
  mapValues,
  cleanEmptyFields,
  sanitizeFormData,
  extractErrorMessages,
} from './objectUtils';

// Browser utilities
export {
  BrowserUtils,
  isSupported,
  getDeviceInfo,
  isMobile,
  isTablet,
  isDesktop,
  getBrowserInfo,
  copyToClipboard,
  downloadFile,
  scrollToElement,
  getScrollPosition,
  debounce,
  throttle,
  localStorage,
  sessionStorage,
  saveUserPreferences,
  getUserPreferences,
  clearUserData,
  trackPageView,
  preloadImage,
  isOnline,
  waitForOnline,
  getViewportSize,
  observeElementVisibility,
} from './browserUtils';

// Types
export type {
  DateFormat,
  TimeFormat,
  CurrencyOptions,
  ValidationRule,
  ValidationResult,
  SortOrder,
  DeviceType,
  BrowserType,
  CoachData,
  SessionData,
  UserPreferences,
} from './types';
